import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

// Platform file size limits in MB
export const PLATFORM_LIMITS = {
  twitter: { video: 512, image: 5 },
  facebook: { video: 1024, image: 8 },
  reddit: { video: 1024, image: 20 },
  instagram: { video: 4096, image: 8 },
};

export const useMediaUpload = () => {
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);

  const getMaxFileSize = (platforms: string[], fileType: 'video' | 'image'): number => {
    // Get the minimum limit across all selected platforms
    let minLimit = Infinity;
    platforms.forEach(platform => {
      const limit = PLATFORM_LIMITS[platform as keyof typeof PLATFORM_LIMITS]?.[fileType];
      if (limit && limit < minLimit) {
        minLimit = limit;
      }
    });
    return minLimit === Infinity ? 512 : minLimit; // Default to 512MB if no platform found
  };

  const validateFile = (file: File, platforms: string[]): { valid: boolean; error?: string } => {
    const fileType = file.type.startsWith('video/') ? 'video' : 'image';
    const maxSize = getMaxFileSize(platforms, fileType);
    const fileSizeMB = file.size / (1024 * 1024);

    if (fileSizeMB > maxSize) {
      return {
        valid: false,
        error: `File size (${fileSizeMB.toFixed(1)}MB) exceeds the ${maxSize}MB limit for selected platforms`,
      };
    }

    // Check file type
    const validVideoTypes = ['video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/webm'];
    const validImageTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
    
    if (fileType === 'video' && !validVideoTypes.includes(file.type)) {
      return { valid: false, error: 'Please upload MP4, MOV, AVI, or WebM video files' };
    }
    
    if (fileType === 'image' && !validImageTypes.includes(file.type)) {
      return { valid: false, error: 'Please upload JPG, PNG, GIF, or WebP image files' };
    }

    return { valid: true };
  };

  const uploadMedia = async (file: File, platforms: string[]): Promise<string | null> => {
    try {
      setUploading(true);
      setUploadProgress(0);

      // Validate file
      const validation = validateFile(file, platforms);
      if (!validation.valid) {
        toast.error(validation.error);
        return null;
      }

      // Get current user
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        toast.error('Please log in to upload media');
        return null;
      }

      // Generate unique filename with user folder
      const fileExt = file.name.split('.').pop();
      const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;
      const filePath = `${session.user.id}/${fileName}`;

      // Upload to Supabase Storage
      const { data, error } = await supabase.storage
        .from('post-videos')
        .upload(filePath, file, {
          cacheControl: '3600',
          upsert: false,
        });

      if (error) {
        throw error;
      }

      // Get signed URL (expires in 1 hour - will be regenerated by edge functions when posting)
      const { data: signedUrlData, error: signedUrlError } = await supabase.storage
        .from('post-videos')
        .createSignedUrl(filePath, 3600); // 1 hour expiry

      if (signedUrlError || !signedUrlData?.signedUrl) {
        throw new Error('Failed to generate signed URL');
      }

      setUploadProgress(100);
      toast.success('Media uploaded successfully!');
      return signedUrlData.signedUrl;
    } catch (error: any) {
      console.error('Error uploading media:', error);
      toast.error(error.message || 'Failed to upload media');
      return null;
    } finally {
      setUploading(false);
      setTimeout(() => setUploadProgress(0), 1000);
    }
  };

  const uploadMultipleMedia = async (
    files: File[],
    platforms: string[]
  ): Promise<string[]> => {
    const urls: string[] = [];
    
    for (const file of files) {
      const url = await uploadMedia(file, platforms);
      if (url) {
        urls.push(url);
      }
    }
    
    return urls;
  };

  return {
    uploadMedia,
    uploadMultipleMedia,
    uploading,
    uploadProgress,
    getMaxFileSize,
    validateFile,
  };
};
